import Foundation
import SwiftData

/// Persists the full history (requirement 1) and manages the on-disk file vault
/// for generated artifacts. All persistence flows through here so there is a
/// single place that guarantees "save everything."
@MainActor
final class HistoryStore {
    private let context: ModelContext
    private let vaultURL: URL

    init(context: ModelContext) {
        self.context = context
        // Prefer the shared app-group container (so widgets/intents can read it);
        // fall back to the app's Documents directory for free-account builds.
        let base = FileManager.default
            .containerURL(forSecurityApplicationGroupIdentifier: "group.com.actig.shared")
            ?? FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        self.vaultURL = base.appendingPathComponent("Vault", isDirectory: true)
        try? FileManager.default.createDirectory(at: vaultURL, withIntermediateDirectories: true)
    }

    // MARK: Conversation

    @discardableResult
    func record(role: TurnRole,
                text: String,
                source: InputSource,
                language: AppLanguage,
                options: [String] = [],
                suggestions: [String] = [],
                vaultItemID: UUID? = nil) -> ConversationTurn {
        let turn = ConversationTurn(role: role, text: text, source: source,
                                    language: language, options: options,
                                    suggestions: suggestions, vaultItemID: vaultItemID)
        context.insert(turn)
        try? context.save()
        return turn
    }

    func recentTurns(limit: Int) throws -> [ConversationTurn] {
        var descriptor = FetchDescriptor<ConversationTurn>(
            sortBy: [SortDescriptor(\.createdAt, order: .forward)]
        )
        descriptor.fetchLimit = limit
        return try context.fetch(descriptor)
    }

    // MARK: Checkpoints

    /// Marks any prior "latest" checkpoint stale and inserts a new one.
    func newCheckpoint(_ checkpoint: WorkflowCheckpoint) {
        if let prior = try? context.fetch(
            FetchDescriptor<WorkflowCheckpoint>(predicate: #Predicate { $0.isLatest })
        ) {
            for c in prior { c.isLatest = false }
        }
        context.insert(checkpoint)
        try? context.save()
    }

    func latestCheckpoint() -> WorkflowCheckpoint? {
        try? context.fetch(
            FetchDescriptor<WorkflowCheckpoint>(predicate: #Predicate { $0.isLatest })
        ).first
    }

    func update(_ checkpoint: WorkflowCheckpoint) { try? context.save() }

    // MARK: File vault

    /// Writes generated bytes to the vault and indexes them. Returns the row so
    /// a `ConversationTurn` can link to it.
    @discardableResult
    func storeFile(data: Data, filename: String, uti: String, note: String = "") -> VaultItem {
        let safeName = "\(UUID().uuidString)-\(filename)"
        let url = vaultURL.appendingPathComponent(safeName)
        try? data.write(to: url, options: .atomic)
        let item = VaultItem(filename: filename, relativePath: safeName,
                             uti: uti, byteCount: data.count, note: note)
        context.insert(item)
        try? context.save()
        return item
    }

    func fileURL(for item: VaultItem) -> URL {
        vaultURL.appendingPathComponent(item.relativePath)
    }
}
